---
name: "Check for Semantic PR and Commit Titles"

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]
  workflow_call:
    inputs:
      COMMITS_HISTORY:
        description: 'Number of commits to consider, starting with most recent (e.g. 1 = only look at most recent).'
        # 250 appears to be the limit of `gh api --paginate $COMMITS_URL`
        default: 250
        required: false
        type: number
      CHECK_PR_TITLE_OR_ONE_COMMIT:
        description: 'If there is one commit, only validate its commit message (and not the PR title). Else validate PR title only (and skip commit messages).  This takes precedence over COMMITS_HISTORY.'
        default: false
        required: false
        type: boolean

env:
  PR_TITLE: ${{ github.event.pull_request.title }}
  COMMITS_URL: ${{ github.event.pull_request.commits_url }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SEMANTIC_PATTERN: |-
__PATTERN__

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Fetch then Check PR Title and Commit Title(s)
      shell: bash
      run: |
__SCRIPT__
