---
name: "Check for Semantic PR and Commit Titles"

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]
  workflow_call:

env:
  PR_TITLE: ${{ github.event.pull_request.title }}
  COMMITS_URL: ${{ github.event.pull_request.commits_url }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SEMANTIC_PATTERN: |-
    ^(Merge .*branch '.+' into|Revert ".+"|(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([^)]+\))?: +[^ ])

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Fetch PR Details
      shell: bash
      run: |
        if [[ $GITHUB_TOKEN ]]; then
          json=$( curl --header "Authorization: Bearer $GITHUB_TOKEN" --fail --retry 3 --silent "$COMMITS_URL" )
        else
          json=$( curl --fail --retry 3 --silent "$COMMITS_URL" )
        fi
        echo 'commits<<EOF' >> $GITHUB_ENV
        echo $json | jq --raw-output '.[] | [.sha, (.commit.message | split("\n") | first)] | join(" ")' >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Check PR Title and Commit Title(s)
      shell: bash
      run: |
        # expected env vars: SEMANTIC_PATTERN, PR_TITLE, commits
        exit_code=0
        
        if [[ ! $PR_TITLE =~ $SEMANTIC_PATTERN ]]; then
          echo ::error::PR title not semantic: "$PR_TITLE"
          exit_code=1
        else
          echo PR title OK: "$PR_TITLE"
        fi
        
        while read -r commit; do
          commit_title=${commit:41}
          commit_hash_short=${commit:0:7}
        
          if [[ ! $commit_title =~ $SEMANTIC_PATTERN ]]; then
            echo ::error::Commit title $commit_hash_short not semantic: "$commit_title"
            exit_code=1
          else
            echo Commit title $commit_hash_short OK: "$commit_title"
          fi
        done <<< $commits
        
        exit $exit_code
